# Note: This action needs to be run on a github-hosted runner, not the self-hosted runner that it shuts-down.

name: "Stop self-hosted runner"

inputs:
  role_arn:
    description: 'The AWS role to assume'
    required: true
  session_name: 
    description: 'The name of the runner session to use'
    required: true
  aws_region:
    description: 'The AWS region to use'
    required: true
  instance_id:
    description: 'The id of the AWS EC2 instance to shut down'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: ${{inputs.role_arn}}
      role-session-name: ${{inputs.session_name}}
      aws-region:  ${{inputs.aws_region}}

    - name: Stop EC2 Instance
      shell: bash
      run: |
        aws ec2 terminate-instances --instance-ids ${{needs.start-runner.outputs.instanceId}}