name: "Set Infrastructure Image Property"
description: "Set the published Image on infrastructure"

inputs:
  image_name:
    description: 'The name of the image being uploaded to the ECR repository'
    required: true
  image_property_name:
    description: 'The name of the corresponding image property in the infrastructure'
    required: true
  github_token:
    description: 'The admin github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
      
    - uses: actions/checkout@v2
      name: 'Checkout Infrastructure Repo'
      with:
        token: ${{ inputs.github_token }}
        repository: 'wildsparq/wildsparq-infrastructure'
        ref: WS-2678-test
        path: './infra'

    - name: Write value to Infrastructure Properties-file
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './infra/.aws/cdk/image.properties'
        property: '${{inputs.image_property_name}}'
        value: '${{inputs.image_name}}'

    - name: 'Commit Image Properties Changes'
      shell: bash
      run: |
        cd ./infra
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add .aws/cdk/image.properties
        git commit -m "update ${{inputs.image_property_name}}"
        git push origin WS-2678-test