name: "Create Versioned Tag"
description: "Tag the current commit of a PR with its resulting version bump"

inputs:
  github_token:
    description: 'A github token with admin access to the repository'
    required: true

outputs:
  version:
    description: 'The created version tag'
    value: ${{steps.return.outputs.tag_to_use}}

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      name: 'Checkout Commit Origin Repo'
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        path: 'origin'
        ref: ${{ env.GITHUB_REF_SLUG_CS }}
        fetch-depth: 0

    - name: Check for existing tag
      id: existing-tag
      shell: bash
      run: |
        cd ./origin
        existing_tag=$(git tag --points-at ${{github.sha}}  --sort=-version:refname  | head -n 1 | xargs)
        echo "existing_tag=$(echo $existing_tag)" >> $GITHUB_OUTPUT


    - name: Get Git Data (Commit Body + Previous Version)
      id: get-git-data
      shell: bash
      if: ${{steps.existing-tag.outputs.existing_tag == '' }}
      run: |
        cd ./origin
        echo $(git status)
        git fetch --quiet
        prev_tag=$(git describe --tags  --abbrev=0 --first-parent || echo "1.0.0")
        echo "prev_tag=$(echo $prev_tag)" >> $GITHUB_OUTPUT
        prev_tag_matching_branch=$(git describe --tags  --abbrev=0 --match "*${{env.GITHUB_REF_SLUG}}*" || echo "0.0.0-${{env.GITHUB_REF_SLUG}}")
        echo "prev_tag_matching_branch=$(echo $prev_tag_matching_branch)" >> $GITHUB_OUTPUT
        body=$(git log -1 --pretty=format:%b ${{github.sha}})
        echo "commit_body=$(echo $body)" >> $GITHUB_OUTPUT


    - name: Setup Python
      shell: bash
      if: ${{steps.existing-tag.outputs.existing_tag == '' }}
      run: |
        sudo apt-get update
        sudo apt-get install python3.6

    - uses: actions/checkout@v2
      name: 'Checkout current Repo'
      if: ${{steps.existing-tag.outputs.existing_tag == '' }}
      with:
        token: ${{ inputs.github_token }}
        repository: wildsparq/.github
        path: 'gh'

    - name: Compute semver
      shell: bash
      if: ${{steps.existing-tag.outputs.existing_tag == '' }}
      id: compute-version
      env:
        PREV_TAG: ${{ steps.get-git-data.outputs.prev_tag }}
        MATCHING_BRANCH_PREV_TAG: ${{ steps.get-git-data.outputs.prev_tag_matching_branch }}
        COMMIT_BODY: ${{steps.get-git-data.outputs.commit_body}}
      run: |
        PIP_BREAK_SYSTEM_PACKAGES=1
        pip3 install semver 
        pip3 install github-action-utils
        python3 ./gh/workflows/scripts/compute-semver.py $PREV_TAG $MATCHING_BRANCH_PREV_TAG "${{ env.GITHUB_REF_SLUG }}" $COMMIT_BODY

    - name: tag/pre-release
      uses: ncipollo/release-action@v1
      if: ${{steps.existing-tag.outputs.existing_tag == '' }}
      with:
         tag: ${{steps.compute-version.outputs.version}}
         prerelease: true
         commit: ${{github.sha}}
         token: ${{ inputs.github_token }}
         allowUpdates: true

    - name: return value
      id: return
      shell: bash
      if: always()
      run: |
        if [ -z "${{steps.existing-tag.outputs.existing_tag}}" ]
          then
            echo "tag_to_use=${{steps.compute-version.outputs.version}}" >> $GITHUB_OUTPUT
          else
            echo "tag_to_use=${{steps.existing-tag.outputs.existing_tag}}" >> $GITHUB_OUTPUT
        fi

