name: "Create Versioned Tag"
description: "Tag the current commit of a PR with its resulting version bump"

inputs:
  # commit:
  #   description: 'The hash of the commit to tag'
  #   required: true
  github_token:
    description: 'A github token with admin access to the repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - uses: actions/checkout@v2
      name: 'Checkout Commit Origin Repo'
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        path: 'origin'
        ref: ${{ env.GITHUB_REF_SLUG_CS }}

    - name: Get Git Data (Commit Body + Previous Version)
      id: get-git-data
      shell: bash
      run: |
        cd ./origin
        git fetch --quiet
        echo "!"
        prev_tag=$(git describe --tags)
        echo "!"
        echo "prev_tag=$(echo $prev_tag)" >> $GITHUB_OUTPUT
        echo "!"
        body=$(git log -1 --pretty=format:%b ${{github.sha}})
        echo "!"
        echo "commit_body=$(echo $body)" >> $GITHUB_OUTPUT
        echo "!"


    - name: setup python
      uses: actions/setup-python@v2

    - uses: actions/checkout@v2
      name: 'Checkout current Repo'
      with:
        token: ${{ inputs.github_token }}
        ref: WS-2160 # TODO: Change
        repository: wildsparq/.github
        path: 'gh'

    - name: run Jira integration script
      shell: bash
      run: |
        pip3 install semver
        python3 ./gh/workflows/scripts/compute-semver.py  ${{steps.get-git-data.outputs.prev_tag}}  ${{ env.GITHUB_REF_SLUG }} "${{steps.get-git-data.outputs.commit_body}}"
