name: "Tag ECR Production Image"
description: "Tags an existing ECR Image as production"

inputs:
  image_tag:
    description: 'The name of the existing image in the ECR repository'
    required: true
  repository_name:
    description: 'The name of the ECR repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::111264134477:role/gitHubimagePublisherRole
        role-session-name: pushToECRSession
        aws-region: us-east-1

    - name: 'Commit Image Properties Changes'
      shell: bash
      run: |
        MANIFEST=$(aws ecr batch-get-image --repository-name ${{repository_name}} --image-ids imageTag=${{image_tag}} --region us-east-1 --output json | jq --raw-output --join-output '.images[0].imageManifest')
        aws ecr put-image --repository-name ${{repository_name}} --region us-east-1 --image-tag production-${{image_tag}} --image-manifest "$MANIFEST"